"use strict";
exports.__esModule = true;
var Repaso2_1_1 = require("./Repaso2.1");
var MobileLibrary_1 = require("./MobileLibrary");
var nokia3210 = new Repaso2_1_1.Mobile();
nokia3210.setName("nokia3210");
nokia3210.setModel("modelo1");
nokia3210.setMark("nokia");
nokia3210.setSD(250);
nokia3210.setColor("blue");
nokia3210.set5G(false);
nokia3210.setCamera(2);
nokia3210.setPrice(200);
var iphone3G = new Repaso2_1_1.Mobile();
iphone3G.setName("iphone3G");
iphone3G.setModel("modelo2");
iphone3G.setMark("apple");
iphone3G.setSD(512);
iphone3G.setColor("black");
iphone3G.set5G(true);
iphone3G.setCamera(4);
iphone3G.setPrice(500);
var samsung = new Repaso2_1_1.Mobile();
samsung.setName("Samsung Galaxy 10");
samsung.setModel("modelo3");
samsung.setMark("samsung");
samsung.setSD(250);
samsung.setColor("red");
samsung.set5G(false);
samsung.setCamera(3);
samsung.setPrice(320);
var alcatel = new Repaso2_1_1.Mobile();
alcatel.setName("Alcatel 20");
alcatel.setModel("modelo4");
alcatel.setMark("alcatel");
alcatel.setSD(512);
alcatel.setColor("black");
alcatel.set5G(false);
alcatel.setCamera(2);
alcatel.setPrice(150);
var todos = [nokia3210, iphone3G, samsung, alcatel];
var libreria = new MobileLibrary_1.MobileLibrary("tienda", "Madrid", todos);
console.log(libreria.getLocation());
console.log(libreria.getMobiles());
console.log(libreria.getName());
console.log(libreria.totalPriceCalculation());
// let moviles = libreria.getMobiles()
// console.log(moviles[0].getPrice())
